### PR TITLE
49 fix roi sizex offsetx errors

### LINKED ISSUE #49: fix roi sizex offsetx errors

### PR DESCRIPTION
**Pull request by subindev-d**
resetting the video setting and sending bin value again to the detector fixed the issue.

### CODE REVIEW

File: pixciApp/src/pixci.h [hunk 1]
```diff
@@ -159,6 +159,13 @@ class Pixci: public ADDriver {
      */
     void reloadVideoSettings();
 
+    /**
+     * @brief reset video settings file to the default. minX , sizeX parameter changes require reset 
+     * video settings in order to reflect in image.
+     * 
+     */
```
Comment (subindev-d) [inline pixciApp/src/pixci.h:166]: rewrite this with resetting binning settings aswell

**Review by aoun-muhammad — APPROVED** [review]
